import type { Language } from '../i18n';
import type { CatKey, Currency } from '../theme';

// Wire shapes returned by the API. Money is always integer minor units (EUR
// cents) — convert with minorToEur() at the render boundary, never before.

export type ApiTransaction = {
  id: string;
  merchant: string;
  category: CatKey;
  /** Signed cents: negative is spend, positive is income. */
  amountMinor: number;
  occurredAt: string;
  note: string | null;
  taxDeductible: boolean;
  /** Which card this was paid with, if any. Null for cash/unlinked spend. */
  cardId: string | null;
  /** Set when this row was generated by a subscription's monthly renewal. */
  subscriptionId: string | null;
  /** What the charge was before conversion, in `originalCurrency`. */
  originalMinor: number | null;
  originalCurrency: Currency | null;
  /** The rate the conversion actually used — frozen, never recomputed. */
  fxRate: number | null;
  /**
   * Set when a bank promo was applied because this was paid with that bank's
   * card. `amountMinor` is already net of it, so the pre-discount total is
   * |amountMinor| + discountMinor.
   */
  discountBank: string | null;
  discountPercent: number | null;
  discountMinor: number | null;
};

export type ApiCategoryTotal = { key: CatKey; spentMinor: number };
export type ApiTrendPoint = { day: string; cumulativeMinor: number };

export type ApiSummary = {
  month: string;
  budgetMinor: number;
  /** Everything spent this month, whatever paid for it. For the donut. */
  spentMinor: number;
  /**
   * What has left the account: spending not put on a card, plus card payments.
   * Anything about how much is left uses this, never spentMinor — a card
   * purchase has not been paid for yet.
   */
  accountOutMinor: number;
  incomeMinor: number;
  safeToSpendMinor: number;
  overBudget: boolean;
  percentOfBudget: number;
  daysLeft: number;
  daysInMonth: number;
  /** Positive means under pace for the month so far. */
  paceDeltaMinor: number;
  pacePercent: number;
  categories: ApiCategoryTotal[];
  trend: ApiTrendPoint[];
};

export type ApiCreditCard = {
  id: string;
  name: string;
  /** Null for cards added in-app — the field is no longer asked for. */
  last4: string | null;
  balanceMinor: number;
  limitMinor: number;
  apr: number;
  color: string;
};

export type ApiSubscription = {
  id: string;
  name: string;
  color: string;
  /**
   * In `currency` — the one the service actually bills in, which is often not
   * the user's. Use priceBaseMinor for anything the user reads as *their* money.
   */
  priceMinor: number;
  currency: Currency;
  /**
   * priceMinor converted to the user's base currency at today's rate, computed
   * server-side. Null when no rate was available — show the native price alone
   * rather than a made-up number.
   */
  priceBaseMinor: number | null;
  dayOfMonth: number;
  muted: boolean;
  off: boolean;
  /** The card the monthly renewal is charged to, if any. */
  cardId: string | null;
  cardName: string | null;
};

export type ApiReceipt = {
  id: string;
  merchant: string;
  amountMinor: number;
  occurredAt: string;
  status: 'ok' | 'warn';
  category: string;
};

export type ApiMessageKind = 'ai' | 'user' | 'voice' | 'receipt' | 'card';

/**
 * What a `card` message proposes. Absent on rows written before card payments
 * and subscriptions existed, which were all plain expenses — so a missing
 * action reads as 'expense' everywhere.
 */
export const CARD_ACTIONS = ['expense', 'income', 'card_payment', 'sub_cancel', 'sub_add', 'sub_edit'] as const;

// Derived from the list rather than written twice, so a new action cannot be
// added to the type while the runtime check that guards old builds forgets it.
export type ApiCardAction = (typeof CARD_ACTIONS)[number];

export type ApiMessage = {
  id: string;
  kind: ApiMessageKind;
  payload: {
    text?: string;
    dur?: string;
    action?: ApiCardAction;
    merchant?: string;
    cat?: CatKey;
    /** Always positive here; the sign is applied when the write happens. */
    amountMinor?: number;
    note?: string;
    /** Where income came from — "Salary", "Dad". Only on `income`. */
    source?: string;
    /** Set when an expense was charged to a card, and on card_payment. */
    cardId?: string;
    cardName?: string;
    /** sub_cancel, sub_add and sub_edit. */
    subId?: string;
    subName?: string;
    dayOfMonth?: number;
    /**
     * The currency the subscription is billed in — `amountMinor` above is in
     * *this*, not the user's. Absent on rows written before subscriptions had
     * a currency of their own, which were all in the user's.
     */
    subCurrency?: Currency;
    /** A bank promo applied to an expense; amountMinor is already net of it. */
    discountBank?: string;
    discountPercent?: number;
    discountMinor?: number;
  };
  createdAt: string;
};

/**
 * A "For you today" card, written by the model once a day (see
 * server/src/insights.ts). Unlike every other shape here it carries *rendered
 * prose* — the amounts are already formatted into `title` and `body`, in the
 * currency the card was generated for — so nothing on this type goes through
 * minorToEur() or formatMoney().
 */
export type ApiInsightIcon = 'trendUp' | 'trendDown' | 'pie' | 'bars' | 'warn' | 'spark' | 'card';
export type ApiInsightAction = 'chat' | 'dashboard' | 'subscriptions' | 'vault';

export type ApiInsight = {
  title: string;
  body: string;
  cta: string;
  icon: ApiInsightIcon;
  /** Where tapping the card goes. A card cannot carry a closure. */
  action: ApiInsightAction;
  /** Receipt id for a `vault` card to deep-link to. Server-validated. */
  targetId: string | null;
};

export type ApiInsights = {
  generatedOn: string | null;
  currency: Currency | null;
  /** True when the client should ask for a regeneration. */
  stale: boolean;
  insights: ApiInsight[];
};

/**
 * A card discount/"reintegro" scraped from a bank's public promo pages (see
 * server/src/scraper/). Global, not user-scoped — every account sees the
 * same rows. `monthlyCapMinor` is always in Paraguayan guaranies regardless
 * of the account's own currency — these are bank-side figures, not this
 * user's data, so they're rendered with formatPYG() directly rather than
 * going through minorToEur()/formatMoney(), which assume the account's own
 * currency convention.
 */
/**
 * Mirrors server/src/scraper/extract.ts's DISCOUNT_CATEGORIES by hand — client
 * and server share no module, the same duplication FACTURAS_ENABLED already
 * uses across both codebases.
 */
export type ApiDiscountCategory =
  | 'groceries'
  | 'restaurants'
  | 'fashion'
  /**
   * Beauty and wellness — salons, spas, barbershops, aesthetic clinics, labs.
   * Pharmacies used to live here and are now split out below.
   */
  | 'beauty_health'
  /**
   * Derived server-side from the merchant's name, never scraped — see
   * server/src/discountCategories.ts. The scraper's own taxonomy has no such
   * category, so this is the one value here that DISCOUNT_CATEGORIES lacks.
   */
  | 'pharmacy'
  | 'home'
  | 'electronics'
  | 'auto_fuel'
  | 'entertainment_travel'
  | 'other';

export type ApiDiscount = {
  bank: string;
  merchant: string;
  category: ApiDiscountCategory | null;
  /** The lower of the bank's tiers (base card, not premium) — see extract.ts. */
  percent: number | null;
  installments: number | null;
  eligibleDays: string | null;
  monthlyCapMinor: number | null;
  validUntil: string | null;
  description: string;
  /**
   * Resolved server-side from the free-text Spanish in `eligibleDays` — see
   * server/src/discountDays.ts. Only true for a discount that is *restricted*
   * to certain days and runs on this one; an always-on discount is false,
   * since it is never news.
   */
  activeToday: boolean;
  /** How many weekdays it runs on, 7 when unrestricted. Lower is more notable. */
  weekdayCount: number;
};

export type ApiSettings = {
  baseCurrency: Currency;
  monthlyBudgetMinor: number;
  /** Which language the app renders in, and the insights are written in. */
  language: Language;
  notif: boolean;
  bio: boolean;
};

/** Cents -> EUR. The one place the minor-units convention is unwound. */
export function minorToEur(minor: number): number {
  return minor / 100;
}

/** EUR -> cents, rounded. Guards against float drift on user input. */
export function eurToMinor(eur: number): number {
  return Math.round(eur * 100);
}
