#!/usr/bin/env node
// Rebuilds .env.local on a new machine, so the file never has to be carried on
// a USB stick or pasted into a chat window.
//
// Every value it needs already exists somewhere authoritative:
//   - the two EXPO_PUBLIC_* vars are committed in eas.json (they are public by
//     design — see "Why the env vars are duplicated in eas.json" in RUNNING.md)
//   - the three secrets are on the VPS in /opt/spendowl/api.env, which is the
//     copy the running API actually reads, so it cannot drift from production
//
// Usage:  node scripts/pull-env.mjs [--force] [--print]
// Needs a working `ssh vps` (see "Setting up a second machine" in RUNNING.md).

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TARGET = join(ROOT, '.env.local');

const force = process.argv.includes('--force');
const print = process.argv.includes('--print');

/**
 * Only these three come off the VPS. The rest of api.env is deliberately left
 * behind: DATABASE_URL points at the box's own 127.0.0.1 Postgres with the
 * box's password, so copying it here would aim local dev at the local Docker
 * container while holding the wrong credentials — an authentication failure
 * that looks nothing like its cause. PORT and NODE_ENV are unit config.
 */
const SECRETS = ['CLERK_SECRET_KEY', 'LLM_API_KEY', 'STT_API_KEY'];
const PUBLIC = ['EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY', 'EXPO_PUBLIC_API_URL'];

function parseEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    out[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
  }
  return out;
}

function die(message, hint) {
  console.error(`\n  ${message}`);
  if (hint) console.error(`  ${hint}`);
  console.error('');
  process.exit(1);
}

if (existsSync(TARGET) && !force) {
  die('.env.local already exists.', 'Pass --force to overwrite it, or delete it first.');
}

// --- the public half: straight out of the committed build config -----------
const eas = JSON.parse(readFileSync(join(ROOT, 'eas.json'), 'utf8'));
const fromEas = eas.build?.preview?.env ?? {};
for (const key of PUBLIC) {
  if (!fromEas[key]) die(`eas.json's preview profile has no ${key}.`, 'It should — check the file was not edited.');
}

// --- the secret half: off the box that actually runs them ------------------
let raw;
try {
  raw = execFileSync('ssh', ['vps', 'cat /opt/spendowl/api.env'], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
} catch (err) {
  die(
    `Could not read /opt/spendowl/api.env over ssh: ${String(err.stderr || err.message).trim()}`,
    'Check `ssh vps` works on this machine first.'
  );
}

const fromVps = parseEnv(raw);
const missing = SECRETS.filter((key) => !fromVps[key]);
if (missing.length) {
  die(`The VPS env file is missing: ${missing.join(', ')}.`, 'Someone changed it — do not guess, go look.');
}

const lines = [
  '# Generated by scripts/pull-env.mjs. Gitignored, and must stay that way.',
  '# Public values come from eas.json; secrets from /opt/spendowl/api.env on the VPS.',
  '',
  ...PUBLIC.map((key) => `${key}=${fromEas[key]}`),
  ...SECRETS.map((key) => `${key}=${fromVps[key]}`),
  '',
].join('\n');

writeFileSync(TARGET, lines, { encoding: 'utf8' });

console.log(`\n  Wrote ${TARGET}`);
for (const key of [...PUBLIC, ...SECRETS]) {
  const value = fromEas[key] ?? fromVps[key];
  const shown = print ? value : `${value.slice(0, 7)}…(${value.length} chars)`;
  console.log(`    ${key.padEnd(36)} ${shown}`);
}
console.log(print ? '' : '\n  Values elided; pass --print to show them.\n');
